name: Java CI - Healthtrack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-maven:
    name: Test Build Maven
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build and Test with Maven
      run: mvn clean verify

  test-selenium:
    name: Test Selenium
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up ChromeDriver 137
      run: |
        wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/137.0.7151.119/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium Tests
      run: mvn test -Dtest=ActualizacionPesoUITest

    - name: Upload Selenium Screenshot
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: selenium-screenshot
          path: selenium/screenshot_google.png

  test-jmeter:
    name: Test JMeter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install JMeter
      run: |
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        echo "$PWD/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

    - name: Run JMeter test plan
      run: |
        mkdir -p jmeter/resultados/html
        jmeter -n -t jmeter/healthtrack_test_plan.jmx -l jmeter/resultados/result.jtl -e -o jmeter/resultados/html

    - name: Upload JMeter HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: jmeter-report
        path: jmeter/resultados/html
